# Generated by Django 3.0.2 on 2020-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextExtract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='image',
        ),
    ]
